#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Button;
                ref class ComboBox;
                ref class ComboBoxItem;
            }
        }
    }
}

namespace ShepherdcastClonerPC
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ Cards;
        private: ::Windows::UI::Xaml::Controls::Button^ Optimized;
        private: ::Windows::UI::Xaml::Controls::TextBox^ FilePath;
        private: ::Windows::UI::Xaml::Controls::Button^ Run;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ DriveC;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ca;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cb;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cc;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cd;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ce;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cf;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cg;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ch;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ci;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cj;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ck;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cl;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cm;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cn;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Co;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cp;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cq;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cr;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cs;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ct;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cu;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cv;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cw;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cx;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cy;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Cz;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ DriveB;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ba;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bb;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bc;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bd;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Be;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bf;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bg;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bh;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bi;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bj;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bk;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bl;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bm;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bn;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bo;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bp;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bq;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Br;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bs;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bt;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bu;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bv;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bw;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bx;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ By;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Bz;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ DriveA;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Aa;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ab;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ac;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ad;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ae;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Af;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ag;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ah;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ai;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Aj;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ak;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Al;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Am;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ An;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ao;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ap;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Aq;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ar;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ As;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ At;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Au;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Av;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Aw;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ax;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Ay;
        private: ::Windows::UI::Xaml::Controls::ComboBoxItem^ Az;
    };
}

